# Heading 1
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5

*Italics*

**Bold**

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,...,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
0,1,3,1,5,72,0,0,0,0,0,...,0,0,1,1,0,1,1,-1,1,1
1,2,3,1,3,144,0,0,0,0,2,...,0,0,0,1,-1,1,1,1,1,1
2,3,3,1,2,58,0,0,0,0,0,...,0,0,0,1,0,-1,1,-1,0,1
3,4,3,1,6,79,1,0,0,0,0,...,0,0,0,1,-1,1,1,1,-1,1
4,5,3,0,4,46,0,0,0,0,0,...,1,0,0,1,1,-1,0,-1,-1,1

In [4]:
df.columns

Index(['id', 'NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash',
       'NumDashInHostname', 'AtSymbol', 'TildeSymbol', 'NumUnderscore',
       'NumPercent', 'NumQueryComponents', 'NumAmpersand', 'NumHash',
       'NumNumericChars', 'NoHttps', 'RandomString', 'IpAddress',
       'DomainInSubdomains', 'DomainInPaths', 'HttpsInHostname',
       'HostnameLength', 'PathLength', 'QueryLength', 'DoubleSlashInPath',
       'NumSensitiveWords', 'EmbeddedBrandName', 'PctExtHyperlinks',
       'PctExtResourceUrls', 'ExtFavicon', 'InsecureForms',
       'RelativeFormAction', 'ExtFormAction', 'AbnormalFormAction',
       'PctNullSelfRedirectHyperlinks', 'FrequentDomainNameMismatch',
       'FakeLinkInStatusBar', 'RightClickDisabled', 'PopUpWindow',
       'SubmitInfoToEmail', 'IframeOrFrame', 'MissingTitle',
       'ImagesOnlyInForm', 'SubdomainLevelRT', 'UrlLengthRT',
       'PctExtResourceUrlsRT', 'AbnormalExtFormActionR', 'ExtMetaScriptLinkRT',
       'PctExtNullSelfRedirectHyperlinksRT', 'CLASS_LABEL'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  10000 non-null  int64
 1   NumDots                             10000 non-null  int64
 2   SubdomainLevel                      10000 non-null  int64
 3   PathLevel                           10000 non-null  int64
 4   UrlLength                           10000 non-null  int64
 5   NumDash                             10000 non-null  int64
 6   NumDashInHostname                   10000 non-null  int64
 7   AtSymbol                            10000 non-null  int64
 8   TildeSymbol                         10000 non-null  int64
 9   NumUnderscore                       10000 non-null  int64
 10  NumPercent                          10000 non-null  int64
 11  NumQueryComponents                  10000 non-null  int64
 12  NumAmpersand                        10000 non-null  int64
 13  NumHash                             10000 non-null  int64
 14  NumNumericChars                     10000 non-null  int64
 15  NoHttps                             10000 non-null  int64
 16  RandomString                        10000 non-null  int64
 17  IpAddress                           10000 non-null  int64
 18  DomainInSubdomains                  10000 non-null  int64
 19  DomainInPaths                       10000 non-null  int64
 20  HttpsInHostname                     10000 non-null  int64
 21  HostnameLength                      10000 non-null  int64
 22  PathLength                          10000 non-null  int64
 23  QueryLength                         10000 non-null  int64
 24  DoubleSlashInPath                   10000 non-null  int64
 25  NumSensitiveWords                   10000 non-null  int64
 26  EmbeddedBrandName                   10000 non-null  int64
 27  PctExtHyperlinks                    10000 non-null  float64
 28  PctExtResourceUrls                  10000 non-null  float64
 29  ExtFavicon                          10000 non-null  int64
 30  InsecureForms                       10000 non-null  int64
 31  RelativeFormAction                  10000 non-null  int64
 32  ExtFormAction                       10000 non-null  int64
 33  AbnormalFormAction                  10000 non-null  int64
 34  PctNullSelfRedirectHyperlinks       10000 non-null  float64
 35  FrequentDomainNameMismatch          10000 non-null  int64
 36  FakeLinkInStatusBar                 10000 non-null  int64
 37  RightClickDisabled                  10000 non-null  int64
 38  PopUpWindow                         10000 non-null  int64
 39  SubmitInfoToEmail                   10000 non-null  int64
 40  IframeOrFrame                       10000 non-null  int64
 41  MissingTitle                        10000 non-null  int64
 42  ImagesOnlyInForm                    10000 non-null  int64
 43  SubdomainLevelRT                    10000 non-null  int64
 44  UrlLengthRT                         10000 non-null  int64
 45  PctExtResourceUrlsRT                10000 non-null  int64
 46  AbnormalExtFormActionR              10000 non-null  int64
 47  ExtMetaScriptLinkRT                 10000 non-null  int64
 48  PctExtNullSelfRedirectHyperlinksRT  10000 non-null  int64
 49  CLASS_LABEL                         10000 non-null  int64
dtypes: float64(3), int64(47)
memory usage: 3.8 MB

In [6]:
df.describe()

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,...,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,...,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,2.445100,0.586800,3.300300,70.264100,1.818000,0.138900,0.000300,0.013100,0.32320,...,0.339600,0.03220,0.030400,0.956600,0.020200,0.353300,0.793200,0.173400,0.314100,0.500000
std,2886.89568,1.346836,0.751214,1.863241,33.369877,3.106258,0.545744,0.017319,0.113709,1.11466,...,0.473597,0.17654,0.171694,0.248037,0.820036,0.888908,0.521019,0.755771,0.897843,0.500025
min,1.00000,1.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,2500.75000,2.000000,0.000000,2.000000,48.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,1.000000,-1.000000,-1.000000,1.000000,0.000000,-1.000000,0.000000
50%,5000.50000,2.000000,1.000000,3.000000,62.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.500000
75%,7500.25000,3.000000,1.000000,4.000000,84.000000,2.000000,0.000000,0.000000,0.000000,0.00000,...,1.000000,0.00000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,10000.00000,21.000000,14.000000,18.000000,253.000000,55.000000,9.000000,1.000000,1.000000,18.00000,...,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
df.nunique()

id                                    10000
NumDots                                  17
SubdomainLevel                           13
PathLevel                                18
UrlLength                               226
NumDash                                  25
NumDashInHostname                        10
AtSymbol                                  2
TildeSymbol                               2
NumUnderscore                            16
NumPercent                               14
NumQueryComponents                       19
NumAmpersand                             16
NumHash                                   2
NumNumericChars                          82
NoHttps                                   2
RandomString                              2
IpAddress                                 2
DomainInSubdomains                        2
DomainInPaths                             2
HttpsInHostname                           1
HostnameLength                           74
PathLength                              147
QueryLength                             164
DoubleSlashInPath                         2
NumSensitiveWords                         4
EmbeddedBrandName                         2
PctExtHyperlinks                       2510
PctExtResourceUrls                     1489
ExtFavicon                                2
InsecureForms                             2
RelativeFormAction                        2
ExtFormAction                             2
AbnormalFormAction                        2
PctNullSelfRedirectHyperlinks          1311
FrequentDomainNameMismatch                2
FakeLinkInStatusBar                       2
RightClickDisabled                        2
PopUpWindow                               2
SubmitInfoToEmail                         2
IframeOrFrame                             2
MissingTitle                              2
ImagesOnlyInForm                          2
SubdomainLevelRT                          3
UrlLengthRT                               3
PctExtResourceUrlsRT                      3
AbnormalExtFormActionR                    3
ExtMetaScriptLinkRT                       3
PctExtNullSelfRedirectHyperlinksRT        3
CLASS_LABEL                               2
dtype: int64

In [8]:
df["NumSensitiveWords"].unique()

array([0, 1, 2, 3])

In [9]:
df.columns = df.columns.str.lower()

In [10]:
df.head()

,id,numdots,subdomainlevel,pathlevel,urllength,numdash,numdashinhostname,atsymbol,tildesymbol,numunderscore,...,iframeorframe,missingtitle,imagesonlyinform,subdomainlevelrt,urllengthrt,pctextresourceurlsrt,abnormalextformactionr,extmetascriptlinkrt,pctextnullselfredirecthyperlinksrt,class_label
0,1,3,1,5,72,0,0,0,0,0,...,0,0,1,1,0,1,1,-1,1,1
1,2,3,1,3,144,0,0,0,0,2,...,0,0,0,1,-1,1,1,1,1,1
2,3,3,1,2,58,0,0,0,0,0,...,0,0,0,1,0,-1,1,-1,0,1
3,4,3,1,6,79,1,0,0,0,0,...,0,0,0,1,-1,1,1,1,-1,1
4,5,3,0,4,46,0,0,0,0,0,...,1,0,0,1,1,-1,0,-1,-1,1

In [11]:
df_2= pd.read_csv('survey.csv')

In [12]:
df_2.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [13]:
df_2.columns

Index(['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [14]:
df_2.describe()

                Age
count  1.259000e+03
mean   7.942815e+07
std    2.818299e+09
min   -1.726000e+03
25%    2.700000e+01
50%    3.100000e+01
75%    3.600000e+01
max    1.000000e+11

In [15]:
df_2.describe(include='all')

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
count,1259,1.259000e+03,1259,1259,744,1241,1259,1259,995,1259,...,1259,1259,1259,1259,1259,1259,1259,1259,1259,164
unique,1246,NaN,49,48,45,2,2,2,4,6,...,5,3,3,3,3,3,3,3,2,160
top,2014-08-27 12:43:28,NaN,Male,United States,CA,No,No,Yes,Sometimes,6-25,...,Don't know,No,No,Some of them,Yes,No,Maybe,Don't know,No,* Small family business - YMMV.
freq,2,NaN,615,751,138,1095,767,637,465,290,...,563,490,925,774,516,1008,557,576,1075,5
mean,NaN,7.942815e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,2.818299e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,-1.726000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2.700000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,3.100000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,3.600000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.000000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_2.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [17]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness_program           1259 non-null   object
 15  seek_help                  1259 non-null   object
 16  anonymity                  1259 non-null   object
 17  leave                      1259 non-null   object
 18  mental_health_consequence  1259 non-null   object
 19  phys_health_consequence    1259 non-null   object
 20  coworkers                  1259 non-null   object
 21  supervisor                 1259 non-null   object
 22  mental_health_interview    1259 non-null   object
 23  phys_health_interview      1259 non-null   object
 24  mental_vs_physical         1259 non-null   object
 25  obs_consequence            1259 non-null   object
 26  comments                   164 non-null    object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

In [18]:
df_2.nunique()

Timestamp                    1246
Age                            53
Gender                         49
Country                        48
state                          45
self_employed                   2
family_history                  2
treatment                       2
work_interfere                  4
no_employees                    6
remote_work                     2
tech_company                    2
benefits                        3
care_options                    3
wellness_program                3
seek_help                       3
anonymity                       3
leave                           5
mental_health_consequence       3
phys_health_consequence         3
coworkers                       3
supervisor                      3
mental_health_interview         3
phys_health_interview           3
mental_vs_physical              3
obs_consequence                 2
comments                      160
dtype: int64

In [19]:
df_2['Age'].unique()

array([         37,          44,          32,          31,          33,
                35,          39,          42,          23,          29,
                36,          27,          46,          41,          34,
                30,          40,          38,          50,          24,
                18,          28,          26,          22,          19,
                25,          45,          21,         -29,          43,
                56,          60,          54,         329,          55,
       99999999999,          48,          20,          57,          58,
                47,          62,          51,          65,          49,
             -1726,           5,          53,          61,           8,
                11,          -1,          72])

Make the columns uniform
There are outliers in the Age column

In [20]:
df_2['Country'].unique()

array(['United States', 'Canada', 'United Kingdom', 'Bulgaria', 'France',
       'Portugal', 'Netherlands', 'Switzerland', 'Poland', 'Australia',
       'Germany', 'Russia', 'Mexico', 'Brazil', 'Slovenia', 'Costa Rica',
       'Austria', 'Ireland', 'India', 'South Africa', 'Italy', 'Sweden',
       'Colombia', 'Latvia', 'Romania', 'Belgium', 'New Zealand',
       'Zimbabwe', 'Spain', 'Finland', 'Uruguay', 'Israel',
       'Bosnia and Herzegovina', 'Hungary', 'Singapore', 'Japan',
       'Nigeria', 'Croatia', 'Norway', 'Thailand', 'Denmark',
       'Bahamas, The', 'Greece', 'Moldova', 'Georgia', 'China',
       'Czech Republic', 'Philippines'], dtype=object)

#### **Data Cleaning**

In [21]:
df_2.columns = df_2.columns.str.lower()

In [22]:
df_2.head()

,timestamp,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [23]:
df_2 = df_2[(df_2["age"] >= 18) & (df_2["age"] <= 60)]
df_2["age"].unique()

array([37, 44, 32, 31, 33, 35, 39, 42, 23, 29, 36, 27, 46, 41, 34, 30, 40,
       38, 50, 24, 18, 28, 26, 22, 19, 25, 45, 21, 43, 56, 60, 54, 55, 48,
       20, 57, 58, 47, 51, 49, 53])

In [24]:
df_2 = df_2.drop(["state", "comments", "timestamp"], axis=1)
df_2.columns

Index(['age', 'gender', 'country', 'self_employed', 'family_history',
       'treatment', 'work_interfere', 'no_employees', 'remote_work',
       'tech_company', 'benefits', 'care_options', 'wellness_program',
       'seek_help', 'anonymity', 'leave', 'mental_health_consequence',
       'phys_health_consequence', 'coworkers', 'supervisor',
       'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence'],
      dtype='object')

In [25]:
#df_2 = df_2.drop("timestamp", axis=1)

In [26]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1247 entries, 0 to 1258
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        1247 non-null   int64
 1   gender                     1247 non-null   object
 2   country                    1247 non-null   object
 3   self_employed              1229 non-null   object
 4   family_history             1247 non-null   object
 5   treatment                  1247 non-null   object
 6   work_interfere             986 non-null    object
 7   no_employees               1247 non-null   object
 8   remote_work                1247 non-null   object
 9   tech_company               1247 non-null   object
 10  benefits                   1247 non-null   object
 11  care_options               1247 non-null   object
 12  wellness_program           1247 non-null   object
 13  seek_help                  1247 non-null   object
 14  anonymity                  1247 non-null   object
 15  leave                      1247 non-null   object
 16  mental_health_consequence  1247 non-null   object
 17  phys_health_consequence    1247 non-null   object
 18  coworkers                  1247 non-null   object
 19  supervisor                 1247 non-null   object
 20  mental_health_interview    1247 non-null   object
 21  phys_health_interview      1247 non-null   object
 22  mental_vs_physical         1247 non-null   object
 23  obs_consequence            1247 non-null   object
dtypes: int64(1), object(23)
memory usage: 243.6+ KB

In [27]:
df_2["no_employees"].unique()

array(['6-25', 'More than 1000', '26-100', '100-500', '1-5', '500-1000'],
      dtype=object)

In [28]:
order = ['1-5', '6-25', '26-100', '100-500', '500-1000', 'More than 1000']

In [29]:
df_2['no_employees'] = pd.Categorical(df_2['no_employees'], categories=order, ordered=True)

In [30]:
df_2["no_employees"].unique()

['6-25', 'More than 1000', '26-100', '100-500', '1-5', '500-1000']
Categories (6, object): ['1-5' < '6-25' < '26-100' < '100-500' < '500-1000' < 'More than 1000']

In [31]:
df_2["no_employees"].value_counts()

no_employees
6-25              288
26-100            288
More than 1000    280
100-500           175
1-5               157
500-1000           59
Name: count, dtype: int64

##### Series methods

```
.unique()
.value_counts()
.mean()
.isna()
.dropna()
.fillna()
```

##### Dataframe methods

```
df.head()
df.tail()
df.describe()
df.info()
df.drop()
df.rename()
df.merge()
df.groupby()
df.sort_values()
df.sort_index()
```

##### Work on both 
```
count()
isna()
fillna()
astype()
```

In [32]:
df_2['gender'].unique()

array(['Female', 'M', 'Male', 'male', 'female', 'm', 'Male-ish', 'maile',
       'Trans-female', 'Cis Female', 'F', 'something kinda male?',
       'Cis Male', 'Woman', 'f', 'Mal', 'Male (CIS)', 'queer/she/they',
       'non-binary', 'Femake', 'woman', 'Make', 'Nah', 'Enby', 'fluid',
       'Genderqueer', 'Female ', 'Androgyne', 'Agender',
       'cis-female/femme', 'Guy (-ish) ^_^', 'male leaning androgynous',
       'Male ', 'Man', 'Trans woman', 'msle', 'Neuter', 'Female (trans)',
       'queer', 'Female (cis)', 'Mail', 'cis male', 'Malr', 'femail',
       'Cis Man', 'ostensibly male, unsure what that really means'],
      dtype=object)

In [33]:
df_2['gender'] = df_2['gender'].str.lower().str.strip()
df_2['gender'].nunique()
df_2['gender'].unique()

array(['female', 'm', 'male', 'male-ish', 'maile', 'trans-female',
       'cis female', 'f', 'something kinda male?', 'cis male', 'woman',
       'mal', 'male (cis)', 'queer/she/they', 'non-binary', 'femake',
       'make', 'nah', 'enby', 'fluid', 'genderqueer', 'androgyne',
       'agender', 'cis-female/femme', 'guy (-ish) ^_^',
       'male leaning androgynous', 'man', 'trans woman', 'msle', 'neuter',
       'female (trans)', 'queer', 'female (cis)', 'mail', 'malr',
       'femail', 'cis man',
       'ostensibly male, unsure what that really means'], dtype=object)

In [34]:
male = [m for m in df_2["gender"] if m.startswith('m') or m.startswith('guy')]
print(male)

['m', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'm', 'male', 'm', 'male-ish', 'maile', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'mal', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'male (cis)', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'm', 'male', 'male', 'make', 'male', 'm', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'make', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'make', 'male', 'make', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'guy (-ish) ^_^', 'male', 'male leaning androgynous', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'man', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'man', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'msle', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'm', 'male', 'm', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'mail', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'malr', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'm', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'm', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'm', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male']

In [35]:
for m in df_2["gender"]:
    if m == 'cis male':
        male.append(m)

In [36]:
female = [f for f in df_2["gender"] if f.startswith('f') or f.startswith('w')]
print(female)

['female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'f', 'female', 'female', 'female', 'female', 'female', 'f', 'f', 'woman', 'female', 'female', 'female', 'f', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'f', 'female', 'f', 'female', 'f', 'female', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'f', 'female', 'f', 'female', 'female', 'female', 'f', 'f', 'f', 'female', 'femake', 'f', 'f', 'f', 'female', 'female', 'woman', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'fluid', 'female', 'female', 'female', 'f', 'female', 'female', 'female', 'f', 'female', 'female', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'f', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'female', 'female', 'woman', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'female', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'f', 'f', 'female', 'f', 'female', 'female', 'female', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female (trans)', 'female', 'f', 'f', 'female', 'female', 'female (cis)', 'female', 'f', 'female', 'f', 'female', 'female', 'female', 'f', 'female', 'female', 'female', 'f', 'female', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'female', 'female', 'f', 'female (trans)', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'f', 'female', 'f', 'female', 'female', 'female', 'f', 'female', 'female', 'woman', 'female', 'f', 'femail', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'female', 'f', 'female', 'female', 'f']

In [37]:
for f in df_2["gender"]:
    if f == 'cis female' or f == 'cis-female/femme':
        female.append(m)

In [38]:
# female.remove('fluid')
female.remove('female (trans)')

In [41]:
def clean_gender(gender):

    if gender in male:
        return 'male'
    elif gender in female:
        return  'female'
    else:
        return 'other'
    
df_2['gender'] = df_2['gender'].apply(clean_gender)

In [43]:
df_2['gender'].unique()

array(['female', 'male', 'other'], dtype=object)

In [46]:
df_2['country'] = df_2['country'].str.lower().str.strip().str.replace(" ", "_")

In [47]:
df_2["country"].unique()

array(['united_states', 'canada', 'united_kingdom', 'bulgaria', 'france',
       'portugal', 'netherlands', 'switzerland', 'poland', 'australia',
       'germany', 'russia', 'mexico', 'brazil', 'slovenia', 'costa_rica',
       'austria', 'ireland', 'india', 'south_africa', 'italy', 'sweden',
       'colombia', 'latvia', 'romania', 'belgium', 'new_zealand', 'spain',
       'finland', 'uruguay', 'israel', 'bosnia_and_herzegovina',
       'hungary', 'singapore', 'japan', 'nigeria', 'croatia', 'norway',
       'thailand', 'denmark', 'greece', 'moldova', 'georgia', 'china',
       'czech_republic', 'philippines'], dtype=object)

In [48]:
df_2 = df_2[df_2["country"] == 'united_states']

In [49]:
df_2.head()

,age,gender,country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,female,united_states,NaN,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,male,united_states,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
4,31,male,united_states,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
5,33,male,united_states,NaN,Yes,No,Sometimes,6-25,No,Yes,...,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No
6,35,female,united_states,NaN,Yes,Yes,Sometimes,1-5,Yes,Yes,...,No,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No

In [50]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 743 entries, 0 to 1258
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        743 non-null    int64
 1   gender                     743 non-null    object
 2   country                    743 non-null    object
 3   self_employed              732 non-null    object
 4   family_history             743 non-null    object
 5   treatment                  743 non-null    object
 6   work_interfere             602 non-null    object
 7   no_employees               743 non-null    category
 8   remote_work                743 non-null    object
 9   tech_company               743 non-null    object
 10  benefits                   743 non-null    object
 11  care_options               743 non-null    object
 12  wellness_program           743 non-null    object
 13  seek_help                  743 non-null    object
 14  anonymity                  743 non-null    object
 15  leave                      743 non-null    object
 16  mental_health_consequence  743 non-null    object
 17  phys_health_consequence    743 non-null    object
 18  coworkers                  743 non-null    object
 19  supervisor                 743 non-null    object
 20  mental_health_interview    743 non-null    object
 21  phys_health_interview      743 non-null    object
 22  mental_vs_physical         743 non-null    object
 23  obs_consequence            743 non-null    object
dtypes: category(1), int64(1), object(22)
memory usage: 140.3+ KB

In [53]:
df_2['work_interfere'].value_counts()

work_interfere
Sometimes    289
Never        122
Rarely       111
Often         80
Name: count, dtype: int64

In [54]:
df_2['work_interfere'] = df_2['work_interfere'].fillna('unknown')
df_2['work_interfere'].value_counts()

work_interfere
Sometimes    289
unknown      141
Never        122
Rarely       111
Often         80
Name: count, dtype: int64